name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  produce:
    runs-on: ubuntu-latest
    steps:
      - name: 결과 파일 생성
        run: |
          mkdir -p out
          echo "Hello" > out/result.txt

      - name: 업로드
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: out/

  
  consume:
    runs-on: ubuntu-latest
    needs: produce
    steps:
      - name: 다운로드
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: downloaded/

      - name: 확인
        run: cat downloaded/result.txt
